99 card donar
duvan29/DaleQueValen pull request #160
Opened 2023-10-03 19:32 UTC by Candeb

![image](https://github.com/duvan29/DaleQueValen/assets/103592768/cf941fe5-1155-4ac8-8dfb-9795aa5ca4ac)

2023-10-03 19:35 UTC, duvan29 requested changes
Cambiar el tamaño para que se vean las cards iguales

2023-10-04 04:55 UTC, Candeb commented
![image](https://github.com/duvan29/DaleQueValen/assets/103592768/c6d36827-df87-4bd0-a932-5db1ea34d9af)

2023-10-04 04:58 UTC, duvan29 requested changes
Las cartas en version desktop deben tener el mismo lugar en boton de accion se puede hacer dandole un mi-h al contenedor que tiene la description

2023-10-04 18:54 UTC, duvan29 approved these changes

2023-10-04 18:55 UTC, merged